# Generated by Django 3.2.9 on 2021-12-30 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subdivision', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rpt',
            unique_together={('name', 'forname')},
        ),
    ]
