# Generated by Django 3.2.9 on 2022-02-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subdivision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpt',
            name='active',
            field=models.BooleanField(blank=True, null=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='rpt',
            name='status',
            field=models.BooleanField(blank=True, null=True, verbose_name='Thésé'),
        ),
    ]
