# Generated by Django 3.2.9 on 2022-02-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subdivision', '0003_auto_20220207_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpt_cost', models.IntegerField(blank=True, null=True, verbose_name='Rpt tarif')),
                ('vac_cost_1', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Vac moins')),
                ('vac_cost_2', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Vac plus')),
                ('gerant', models.CharField(blank=True, max_length=50, null=True, verbose_name='Gerant')),
            ],
            options={
                'verbose_name': 'Comptabilite',
            },
        ),
    ]
