# Generated by Django 3.2.9 on 2021-12-02 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subdivision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeskRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Salle Consultation',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='HourChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure', models.CharField(blank=True, max_length=5, null=True, verbose_name='Heure')),
                ('period', models.CharField(blank=True, choices=[('Matin', 'Matin'), ('Apm', 'Après-midi')], max_length=10, null=True, verbose_name='Période')),
            ],
            options={
                'verbose_name': 'Heure',
                'verbose_name_plural': 'Heures',
                'ordering': ['heure'],
            },
        ),
        migrations.CreateModel(
            name='Iade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom')),
                ('forname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Prénom')),
                ('phone_hop', models.CharField(blank=True, max_length=5, null=True, verbose_name='Poste')),
                ('telmob', models.CharField(blank=True, max_length=12, null=True, verbose_name='Tél. Mob.')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('statut', models.CharField(blank=True, choices=[('sal', 'Salarié'), ('vac', 'Vacataire')], max_length=12, null=True, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'IADE',
                'verbose_name_plural': 'IADEs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Interne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom')),
                ('forname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Prénom')),
                ('telmob', models.CharField(blank=True, max_length=12, null=True, verbose_name='Tél. Mob.')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Interne',
                'verbose_name_plural': 'Internes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('speciality', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Opérateur',
                'verbose_name_plural': 'Opérateurs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RepartEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='RPT', max_length=10, null=True, verbose_name='Type')),
                ('description', models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='Résumé')),
                ('title', models.CharField(default='Répartition :  ', max_length=100, verbose_name='Répartition')),
                ('start', models.DateField(unique=True, verbose_name='Date')),
                ('start_time', models.TimeField(default='00:00:00', verbose_name='Heure début')),
                ('end', models.DateField(blank=True, null=True, verbose_name='Fin')),
                ('end_time', models.TimeField(default='00:00:00', verbose_name='Heure Fin')),
                ('is_cancelled', models.BooleanField(blank=True, default=False)),
                ('all_day', models.BooleanField(blank=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('duty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='are_repart', to='subdivision.are', verbose_name='Anesthésiste')),
                ('sspi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sspi', to='subdivision.are', verbose_name='SSPI')),
            ],
            options={
                'verbose_name': 'Répartition',
                'verbose_name_plural': 'Répartitions',
                'ordering': ['-start'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Secteur',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=10, null=True)),
                ('sortnum', models.IntegerField(blank=True, null=True, unique=True)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repartition.sector')),
            ],
            options={
                'verbose_name': 'Salle',
                'ordering': ['sortnum'],
            },
        ),
        migrations.CreateModel(
            name='RepartLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(blank=True, choices=[('Matin', 'Matin'), ('Apm', 'Après-midi')], max_length=10, null=True, verbose_name='Période')),
                ('are', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='repart_are', to='subdivision.are', verbose_name='Anesthésiste')),
                ('iade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='repart_iade', to='repartition.iade', verbose_name='IADE')),
                ('interne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='repart_int', to='repartition.interne', verbose_name='Interne')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='operator', to='repartition.operator', verbose_name='Opérateur')),
                ('repart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repartition', to='repartition.repartevent')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='room', to='repartition.room', verbose_name='Salle')),
                ('rpt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='repart_rpt', to='subdivision.rpt', verbose_name='Remplaçant')),
                ('start_time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='heuredebut', to='repartition.hourchoice', verbose_name='Heure')),
            ],
            options={
                'verbose_name': 'Ligne répartition',
                'verbose_name_plural': 'Lignes répartitions',
                'ordering': ['-repart', 'room'],
                'unique_together': {('repart', 'room', 'period')},
            },
        ),
        migrations.CreateModel(
            name='RepartCs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(blank=True, choices=[('Matin', 'Matin'), ('Apm', 'Après-midi')], max_length=10, null=True, verbose_name='Période Cs')),
                ('are', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cs_are', to='subdivision.are', verbose_name='ARE Cs')),
                ('deskroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cs_deskroom', to='repartition.deskroom', verbose_name='Salle Cs')),
                ('repart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cs_repart', to='repartition.repartevent')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['-repart', 'deskroom'],
                'unique_together': {('repart', 'deskroom', 'period')},
            },
        ),
    ]
