# Generated by Django 3.2.9 on 2021-12-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repartition', '0002_room_exportnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='gsm',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='secretary',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
