# Generated by Django 3.2.9 on 2021-12-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repartition', '0004_auto_20211210_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iade',
            name='statut',
            field=models.CharField(blank=True, choices=[('Salarié', 'Salarié'), ('Vacataire', 'Vacataire')], max_length=12, null=True, verbose_name='Statut'),
        ),
    ]
