# Generated by Django 3.2.9 on 2021-12-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repartition', '0005_alter_iade_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='zone',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
