# Generated by Django 3.2.9 on 2021-12-26 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subdivision', '0001_initial'),
        ('repartition', '0006_operator_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='repartevent',
            name='calendrier',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='subdivision.calendrier', verbose_name='Calendrier'),
        ),
    ]
