# Generated by Django 3.2.9 on 2022-02-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0002_alter_vacation_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='end_time',
            field=models.TimeField(default='15:00:00', verbose_name='Heure Fin'),
        ),
    ]
