# Generated by Django 3.2.9 on 2022-02-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0003_alter_vacation_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacataire',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Couleur'),
        ),
    ]
