# Generated by Django 3.2.9 on 2022-02-17 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subdivision', '0003_auto_20220207_1947'),
        ('vacations', '0004_vacataire_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacataire',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subdivision.webcolor', verbose_name='Couleur'),
        ),
    ]
