# Generated by Django 3.2.9 on 2022-02-23 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0006_vacation_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacation',
            options={'ordering': ['-start', '-start_time'], 'verbose_name': 'Vacation', 'verbose_name_plural': 'Vacations'},
        ),
    ]
