# Generated by Django 3.2.9 on 2022-02-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0007_alter_vacation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='end',
            field=models.DateField(blank=True, default=models.DateField(verbose_name='Début'), null=True, verbose_name='Fin'),
        ),
    ]
