# Generated by Django 3.2.9 on 2022-02-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0008_alter_vacation_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='Fin'),
        ),
    ]
