# Generated by Django 3.2.9 on 2021-12-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repartition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='exportnum',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
